# Generated by Django 3.1.2 on 2022-01-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='idrac_User',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
