# Generated by Django 3.1.2 on 2022-01-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
