# Generated by Django 3.1.2 on 2022-01-12 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20220105_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
